name: Verson Tag
run-name: ${{ github.actor }} start with version 🚀
on:
  push:
      tags:
       - '*'
jobs:
  Version-Commit-Tag:
    runs-on: ubuntu-latest
    steps:
     - name: GitHub Tag Name example
       run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"
