name: Verson Tag
run-name: ${{ github.actor }} start with version 🚀
on: [push]
jobs:
  Version-Commit-Tag:
    runs-on: ubuntu-latest
    steps:
    - id: get_version
      name: Get version
      uses: jannemattila/get-version-from-tag@v3

    - name: Display version
      run: |
        VERSION=$(echo "${{ steps.get_version.outputs.version }}")
        echo $VERSION
